// DailyDialog dataset containing 1000+ conversational sentences for the scramble game.
const SENTENCES = [
  "Good evening. Where have you come from?",
  "May I ask how many people there will be in the party?",
  "What do you mean? It's a scrim.",
  "What do you think of that situation comedies showed every weekend?",
  "How many do you intend to order for our shirts?",
  "Hi, Maggy, Did you hear about David?",
  "That's splendid. Can you take three pictures of me with them?",
  "I suggest that you go to the lawyers'office to get some help.",
  "Great, I want it spicy.",
  "How much did you want to spend?",
  "These are specially designed for the year 2000!",
  "Do you want me to show you where I found them?",
  "OK, sir. I will show you your table.",
  "Whose house warming party is it?",
  "Can you give her a message, please?",
  "Hi! Dick. Where are you going? You're in such a hurry.",
  "Coming. What do you want today?",
  "You have not fulfilled your lease agreement yet.",
  "Should we be here, Alice? I don't think it's that serious.",
  "No, thank you.Please tell him to phone me when he comes back.",
  "Wow! You really like fruit, huh? You've already had 3 plates!",
  "Yes.She teaches our class three times a week.",
  "Does it ever get that cold on here?",
  "Hello, I hope to get a room for the night.",
  "Hello, Room Reservation Service. May I help you?",
  "May I call you at your home about our final decision?",
  "Honey, which hand should I use to hold the fork?",
  "I'm really not going to cook tonight.",
  "Till the end of the month.",
  "How do you like this one? It's very beautiful.",
  "Ok, I will go there myself.",
  "All right. Hop in, please.",
  "Nobody told me that before.",
  "Good. You will feel better after you do.",
  "You had an art class?",
  "Welcome back, Sir. I trust the materials were helpful to you?",
  "OK. I will catch you later.",
  "May I try on this pair of shoes?",
  "What kind of intermediary is it?",
  "Steven, are you talking to me?",
  "I noticed they've taken our radio and left the television.",
  "Basically, there are 7 types of games",
  "how is your house hunting going?",
  "Ice cream, fresh fruit or chocolate cake.",
  "For suspicion of driving under influence.",
  "I bet that Lee wasn't too happy with that!",
  "Excuse me, sir. May I help you?",
  "There's a game on tonight. You want to watch it with me?",
  "Could you bring me some food, please?",
  "You mean you want to stay at home?",
  "Oh, well. If I must, I must.",
  "The question is, can he have it done before Friday?",
  "Should I bring you some water?",
  "I don't know, but I feel terrible.",
  "Would you mind waiting? I'm on the telephone.",
  "No one has ever checked me for allergies.",
  "Where are you going this summer vacation?",
  "Thank you, Steve. You're always so encouraging.",
  "And bugs. They can catch anything.",
  "Can you sew on these buttons?",
  "I was late for work because of them.",
  "May I ask the date of your birth?",
  "To tell you the truth, it's the most tedious course I'ever had.",
  "You look bright-eyed and bushy-tailed.",
  "Oh look! Here it comes now!",
  "About nine thirty in the morning.",
  "Good moming.What can I do for you?",
  "You can get one in the grocery store over there.",
  "Be brave, young man. Only girls cry when given an injection.",
  "It is in front of you.",
  "The cream and sugar are on the table, sir.",
  "I stayed up all night writing a report.",
  "Really? So do you have some specialties?",
  "Do you want me to give you a ride?",
  "It has fifty parking spaces.",
  "What did you do over the weekend?",
  "No, I want to go to the movies instead.",
  "I think so too. How much is it?",
  "Do you have your own circle of friends?",
  "Plaza Hotel, good morning. Leo speaking.",
  "Your bags will be here shortly.",
  "Where? I don't see it.",
  "He must be mad! Nick is a loan shark.",
  "I made a reservation three days ago.My name is George Smith.",
  "Excellent. Would you like anything else?",
  "I've just got the examination results. I am afraid you haven't passed.",
  "Use the number on the back of your library card.",
  "I'm going to let Bob know about the merger.",
  "I need to go to the police station.",
  "What? How much do you know Hollywood?",
  "You mean it will arrive two hours later than usual?",
  "Yes. My name is Lin Tao, the director of Guangzhou Computer Corporation.",
  "Just buy a cask of wine. Have you bought ice yet?",
  "What are the requirements to apply for the position?",
  "What you said gives me the creeps!",
  "Playing the chess is very exhausting, isn't?",
  "Excuse me, miss. What's the tour time we have?",
  "What department did you study in?",
  "Yes, I had a wonderful time.",
  "Yeah, I take this bus all the time.",
  "You might be right. He does think pretty highly of himself.",
  "Fine! Will you need part-time or full-time work?",
  "OK. I look forward to working with you. Enjoy your week!",
  "Nice to see you too. It's been a long time.",
  "I saw garlic ice cream on the menu once.",
  "I would like that. Thank you.",
  "So are Copernicus and many others.",
  "She doesn't mind if you don't mind getting your feet stepped on.",
  "Ok that sounds good. Where shall I meet you?",
  "Good morning, sir. Have a seat please.",
  "For here or to go?",
  "Some people aren't very considerate.",
  "Then you'll have to think of something better, Robert.",
  "Winter is great. I wish it didn't get so cold sometimes though.",
  "And a storm blew our roof away.",
  "What sort of western food do you like best?",
  "This is right. There is no doubt in my mind.",
  "Can I go in to look for a job at their office?",
  "I see. Does he live by himself?",
  "It's Smith. Here is my driver's license.",
  "Actually, I ate too much pork yesterday. I fancy a change.",
  "Should we remember all the new words and expressions?",
  "Yes, I think so. How much are they?",
  "Where is my back pack?",
  "And Sharon Stone is Batwoman?",
  "Dave then? Dave is a spy for WebTracker? You can't be serious.",
  "How is your appetite today?",
  "I'm terrible sorry. I seem to have mislaid your MP4.",
  "Tell me which direction it should be going.",
  "I did not. It looks perfectly fine.",
  "Off campus or on campus?",
  "Definitely. Oh, do you have a reference letter?",
  "Absolutely. Take my word for it.",
  "I come to try my new suit. Here's the receipt.",
  "A soft seat or hard one?",
  "Sure, what can I do for you?",
  "This is Alex. Remember? This is Sean.",
  "Excuse me. I'm ready to order.",
  "Thanks for reminding me. It always slips my mind.",
  "Hold on for a moment please. I'm fetching my textbook.",
  "10 pence off if you use this coupon.",
  "If that's the case, there is nothing more to be said.",
  "May I fix an appointment with Dr.Cui?",
  "I think you should work out more too.",
  "Just fine, thank you.How's your father today?",
  "OK, Dead Man. If this doesn't start your engine, nothing will.",
  "But they are showing what will be all the rage next year.",
  "Where exactly is the pipe?",
  "Can I use the clippers?",
  "Cash. But first, I need a lid for this pan.",
  "Your Rose is a fool.",
  "What are you doing now, Steven?",
  "Same here. I have't brought any new clothes for three months.",
  "All right. Please wait for a minute.",
  "Sorry to hear that. What happened?",
  "Not really, I like watching horror movies, like'The Unborn.'",
  "Say, I like racquetball, too.",
  "Definitely pre-med. What about you?",
  "No, I couldn't fall asleep last night.",
  "you mean you got working experience, right?",
  "Sometimes I'm too tired to eat anything at all.",
  "But if we're going to be late?",
  "Good morning. How can I help you?",
  "I would like to do that.",
  "I didn't know you liked old movies.",
  "Should I date Tom or should I date Harry?",
  "I would be happy to answer any questions you might have.",
  "Here it is, and here we are.",
  "Have you ever been a student leader?",
  "How much is the ticket?",
  "Just trim vegetables for cooking. I will cut up the meat.",
  "What is the customer's name, and what is his room number?",
  "Excuse me, is this the office of the Textile Corporation?",
  "you should have kept trying.",
  "I want to know how to buy something from this machine.",
  "I see why it lags behind other towns.",
  "Would you go to the bookstore with me?",
  "With everything, with everybody, with all this!",
  "But, well... what I want to say is...",
  "Yes, please. Thank you very much.",
  "Would you please ask him to call Chris when he gets back?",
  "Dad, it makes no sense.",
  "Sure. Do you have my number?",
  "Don't you see I'm trying my best?",
  "Can I see the paper when you're through, Sally?",
  "Hello, is that 2896919 16?",
  "He has to deliver letters every day.",
  "Yes. My only recreation is skateboarding.",
  "Me too. I'll talk to you later.",
  "So, what was the best thing about your trip?",
  "Really? Let me check it.",
  "I feel I really stupid.",
  "Do you have enough time to get the right amount of sleep?",
  "Why do you want to leave the company?",
  "Oh, yeah! He can sit down, roll over, and even play dead.",
  "I've been so stressed these days.",
  "Thank you very much. I hope you enjoy your stay.",
  "Then what? Your plane was three hours late!",
  "Oh, there comes the bus.",
  "How long is the ride?",
  "But I always wanted to try it.",
  "No, not for this country.",
  "I'm fine, thanks. And you?",
  "Sure. Come on it. We just finished rebuilding everything.",
  "That sounds good. How are you doing, Linda?",
  "Most willingly. It's 600 dollars per ton.",
  "It's a bit small but looks nice.",
  "But they're purple. I prefer a brown set.",
  "Would you like to call home?",
  "In fact, They'll stretch a bit later.",
  "Have you checked the connections on your computer?",
  "Yes, could you please put me in the non-smoking section?",
  "Hey, Anna, this is Jason.",
  "You'll recover after a good night's sleep.",
  "There you are. As you can see, the maturity isn't up yet.",
  "What? What is it? What's the matter?",
  "Show us our itineraries, please.",
  "What do you think about our company?",
  "I see. Do you love pets?",
  "Fill in this slip in ink, please.",
  "How do you like you dishes today?",
  "Not from this brand, I'm afraid.",
  "Wow! You're right! This refrigerator is great. I'll take it.",
  "Would it cost a lot more?",
  "OK, please wait for a moment.",
  "That's a relief for me and a misery for the children.",
  "In 2002. And since then he has attracted more attention than ever.",
  "It will begin at 5 thirty.",
  "Of course. Here is the fitting room.",
  "There must be something wrong with her.",
  "What kind of currency do you want?",
  "Would you please put that cigarette out? I get sick on it.",
  "That's a good idea. Why have I never thought of that?",
  "OK. Can you give me a fragile label?",
  "Are you satisfied with your girlfriend?",
  "Do I have any fees to pay?",
  "Do you have any complaints?",
  "Have you received any degrees?",
  "That's fine. By the way, do you quote FOB or CIF?",
  "Excuse me, miss. I'm Bob.",
  "Of course. I fed them today.",
  "Do you think you could keep the noise down?",
  "Me, too. I miss you. Are you any better?",
  "Can you help me find a pan?",
  "OK... just grab it right out of my hands...",
  "You can catch it on Altadena Drive.",
  "I know. What time do they go?",
  "Thank you. That's very nice of you.",
  "I'm fine for now, thanks.",
  "Well, if you think you are ready, I'll let you enroll.",
  "What does he look like? Can people tell?",
  "Bye! I'll be back before seven.",
  "Would you show me this brooch?",
  "OK, I see. Thank you!",
  "Fortunately, she's not seriously injured.",
  "Her parents scolded her severely and she's very depressed now.",
  "I just love your hair that way.",
  "Extremely good. I shot a 78, including 5 birdies!",
  "Cockroaches have taken over my room!",
  "I started playing starcraft and ended up wasting a lot of time.",
  "I guess you'll read the fine print next time, won't you!",
  "Really. What do they mean?",
  "Yes. That would be better.",
  "Good morning, this is Mary.",
  "Wait, that guy, I know him. He is just a bench warmer.",
  "I want to try my hand at the stocks.",
  "I am going to the Central Park. Which train should I take?",
  "Well, all the drinks including beer are free of charge.",
  "But I'm afraid it will take too much of my time.",
  "what do you think of studying abroad?",
  "Do you want to eat breakfast here?",
  "Fine, I'd like two enlargements from this negative.",
  "Do you know what you're going to do this weekend?",
  "I want some kind of dessert.",
  "He's a member of the National Basketball Association.",
  "Sporting goods? Is that bike Tim wanted on sale?",
  "It seems that you don't like him.",
  "How far is it from here to the airport?",
  "They're on special this week. They've been reduced to five dollars.",
  "Who are the bad guys?",
  "Well, I would like a glass of warm water.",
  "It was after 2 am.",
  "What are your plans for the future if you are hired?",
  "I always make my salads with shredded cheese, croutons, and almonds.",
  "It really was. You should've gone.",
  "Why do you want to join us?",
  "The heel is a little tight.",
  "I'd like to order room service to room 202, please,",
  "If you asked me, you've got a screw loose somewhere.",
  "How much do I need to pay for it?",
  "No way, if it still has 21.",
  "How long has the company been in business?",
  "Jack, could you check your calendar?",
  "Dear Anna. I really love you.",
  "what kinds of tv programmes do you enjoy watching?",
  "I'll pay for it with a check.",
  "Ah... No, I can't place her.",
  "Is that where you park?",
  "No. It's no problem.Are you American?",
  "Sure, I will. Thank you for inviting me.",
  "Yes, I need this prescription please.",
  "That's a beautiful city. When do you want to go there?",
  "I hope you're not turning into a sissy on me, Dave.",
  "Please wake me up at seven tomorrow morning.",
  "How do you like other films starring Charlie Chaplin?",
  "You mean he had been put in prison before.",
  "Excuse me, is this the parcel post counter?",
  "Let's see. From here, you have to take the 278 bus.",
  "Autumn is the best season in Beijing, you know.",
  "What can I do to help you?",
  "Why not? We're supposed to meet him there.",
  "Tom, did you see the film last night?",
  "What happened to your car?",
  "But I need someone that I can count on for this job.",
  "Don't be so happy, it is just one of my tests!",
  "And the second stage is called a tornado warning.",
  "I wasn't aware that I had to go to court.",
  "Usually we have a month off.",
  "And please send this letter by registered mail.",
  "A nice name, isn't it?",
  "OK, I will present your counter-offer to the owners tonight.",
  "What have you been up to?",
  "I'll help you with your homework.",
  "I am really enjoying it here so far.",
  "Please fasten your seat belt, miss.",
  "No, I didn't. How high is the tax?",
  "That's true. We can not judge people by appearance.",
  "Shall we go downtown for a movie this Friday evening?",
  "How do you think if I volunteer for some work?",
  "If so, we may live there someday.",
  "I think you've got a cold.",
  "When do you start school?",
  "I am glad we've straightened everything out.",
  "There is no step four...",
  "Hello, I've got a letter here that I'd like to post.",
  "Mary, today a man from an intermediary gave me a call.",
  "My wife and me. The two of us.",
  "May I have a reservation?",
  "So when did this all happen?",
  "In America, most children start primary school at the age of five.",
  "Yes, it almost looks new.",
  "Right! Glad to see you here.",
  "Now let's have one together.",
  "At least five channels have morning cartoons on Saturdays.",
  "I really enjoyed the food.",
  "I see. Are there any seat available?",
  "May and Daniel often like this kind of weather.",
  "Oh, my computer crashed again!",
  "I understand. They think a tornado might come.",
  "Of course. Otherwise I cannot go abroad.",
  "Are you serious? How can that be?",
  "Yes, you get off at the square.",
  "I've tried, but it didn't work.",
  "Are you planning a trip to the Outback?",
  "New York University hospital in New York City. What do you do?",
  "Ok, six thirty AM. We will call you exactly on that time.",
  "That's true. Many people from the south don't like the weather here.",
  "Hope to see you again. We will provide the best service.",
  "Yes, would you please call me a taxi first?",
  "Certainly.It has been specially treated.",
  "do you have anything to declare?",
  "While the pale color symbolizes beauty and elegance in most Asia countries.",
  "I will pay with cash.",
  "Yes. I commute five days a week by train.",
  "Anything good for this evening?",
  "Yeah, he tackled him so hard his helmet came off.",
  "Yes, I did. Have you lived here long?",
  "At six thirty AM tomorrow.",
  "I said you can trust him. You just have to believe it.",
  "Oh, cash will be fine.",
  "I usually shop at Sons.",
  "So I'll see you tomorrow then at 8.",
  "I park days and evenings.",
  "Fine! I'll be back by nine then. Don't worry.",
  "Oh my, no internet access is killing me.",
  "I don't know. It looks a little wrong down.",
  "Good morning, Mr. Yang. Thank you very much. Can I work now?",
  "No, but I'd like to get something typical in this region.",
  "Great! It's good to see you. Goodbye!",
  "No, I feel young, fresh and energetic.",
  "What's the price for this one?",
  "Thank you. You'Ve been very helpful.",
  "It only takes 45 minutes to an hour.",
  "Is there an alarm system in the apartment?",
  "Do you feel like going to see a movie tonight?",
  "Sure, no problem. What are you trying to get?",
  "do you want to listen to your messages first?",
  "Well, why not try Spaghetti Bolognese?",
  "Yeah, but that's human nature.",
  "I love that shirt on you.",
  "Hello, I'm sorry for calling this late. May I speak to Peter?",
  "Certainly, what time will you come back?",
  "Thirty bucks a record. Or five for one hundred and twenty bucks.",
  "Have you finished that report yet?",
  "Do you prefer some specific style?",
  "Yes, we are. What position are you looking for?",
  "Dalian is a beautiful city. Do you agree?",
  "Why do you want to work in our company?",
  "Are you interested in science? I can't believe it.",
  "You must have left it somewhere.",
  "A friend told me might find a room here.",
  "Why don't you start cooking then?",
  "That's wonderful! Icing on the cake.",
  "I would be happy to. Did you find everything you needed?",
  "I would like you to fix the problem.",
  "Of course! Let me take it out of my wallet.",
  "Are you laughing at me?",
  "How's Mrs Zu doing these days?",
  "Have you decided which city you want to go?",
  "I would like to know is it a direct flight to Dubai?",
  "Oh, yeah, let's try to find some jobs.",
  "Yes, a single room for March 28.",
  "No. I think I've known enough. Thank you.",
  "Will this table be all right?",
  "that depends. What is it?",
  "It seems a glorious day today.",
  "Can you give me a better deal?",
  "Oh, yes. I know where it is.",
  "It's two blocks down the road.",
  "I think we should buy some souvenirs to take home.",
  "It's so nice of you.",
  "Oh, sorry to have bothered you.",
  "Yeah, I come here every now and then.",
  "but I still love you.",
  "I'd like two kilos of eggs.",
  "What are you doing, Victor?",
  "It wasn't a dirty movie. There wasn't even any nudity.",
  "I know, and we've been on the bus forever.",
  "What are your plans for the future?",
  "It's going to be 3 dollars 40 cents.",
  "I love this art exhibition!",
  "I want to go back to school.",
  "I don't make idle threats.",
  "You got a letter in the mail.",
  "It doesn't look very nice outside today.",
  "I have heard of that before. When shall we start?",
  "what do most of the students do?",
  "Thank you for agreeing to come in and meet with us today.",
  "So you have to open all the envelopes.",
  "You're right. And I also meet many new friends while collecting stamps.",
  "I've just had an argument with Bob.",
  "Yes, I'd like to buy these razors.",
  "Did you watch TV last night, Rose?",
  "And that's it. You're done.",
  "I won't be paying you for this.",
  "Yes. So what else to do now?",
  "You're right! I will call him this weekend and meet him.",
  "May I turn on the TV then?",
  "What about all these other pieces?",
  "How long have you been washing clothes here?",
  "Do you need to file copies of the letters before sending them?",
  "That will be best. I'd like to have a good rest first.",
  "How can I tell her about this?",
  "Stop it. No more of that talk.",
  "I have a sore throat and my chest hurts.",
  "It wouldn't rain in the middle of the summer.",
  "Then I'll see you at six. Is that all right?",
  "I'd just like a trim, and don't cut it too short.",
  "You'll be able to take the test again in a couple weeks.",
  "Okay, I'll let you sleep for a little while longer.",
  "Is this the class to prepare for interviews?",
  "Yes. Here is my passport.",
  "it's a letter from Ray and Sue in Shanghai!",
  "That's true. During rush hours, taxis are just as quick as buses.",
  "Come on! It's time to go!",
  "I would like to make a deposit.",
  "I know, but I still get my license, right?",
  "Guangzhou. I've got a cousin there.",
  "Mom, happy Mother's Day! A necklace for you.",
  "You mustn't pick it in this place.",
  "Yeah, let me have a try.",
  "I'm going to go hiking. Do you want to join me?",
  "I know and they are really nice, too.",
  "No, I have not seen the signs.",
  "Sir, our guests are our reason for being.",
  "Just get online and send your application through email to the employer.",
  "Just as you advertised in the newspaper.",
  "I need to hire you.",
  "Did you join in any club activities?",
  "I meant that they're very simple, easy to talk to.",
  "Fine. I'll be ready in a minute.",
  "Ok, I will bring you photos as many as possible.",
  "Do you want to buy something here?",
  "Well, this one is not compulsory. It is just suggestion.",
  "Northward Airlines. Can I help you?",
  "I'll surely make introductions for them.",
  "I agree. He is also an excellent speaker.",
  "That's a good idea. You are really creative.",
  "Of course, he was our monitor in college. How is him now?",
  "I hope to do a little gardening. I find it very relaxing.",
  "Thirty for each adult, twenty each kid.",
  "What's the price for that suit?",
  "One last thing. Is it waterproof?",
  "No problem. See you next Monday.",
  "Hello, there. What can we do for you today?",
  "Can you tell her I'm waiting to speak to her?",
  "Let me get that package.",
  "I see. Then what about tomorrow, at Starbucks?",
  "you should be. You worked really hard last night preparing for it.",
  "I want to make a long distance phone call.",
  "Oh, that means I can do whatever I like without few interruptions.",
  "I didn't really like it.",
  "OK, that's fine. Could you hold it for me?",
  "Do you often do exercise?",
  "Well. We went bungee jumping when we were in Malaysia.",
  "Great, do you still remember when he started his voyage?",
  "Oh, Mom, I think I'm not the right person for swimming.",
  "Oh! I'm sorry, but I wish you could stay.",
  "I call the landlord right now.",
  "I hear your daughter graduated from high school as the valedictorian.",
  "that's the one. It's an actioncomedy. What do you think?",
  "What time shall we start?",
  "That is quite a lot of money for just one month.",
  "How long will it take for them to get here?",
  "Yeah. I found it is so close to our life.",
  "Maybe you should think about moving.",
  "Really? And what led you to this conclusion?",
  "The same to you. Keep in touch.",
  "Oh, she's nice. How much is she?",
  "But not enough space for me?",
  "Can you speed up a bit?",
  "All right. Yes, he does. The registration fee is 7 yuan, please.",
  "What forms should I fill out to collect unemployment?",
  "No. I heard that's really boring.",
  "Maybe he is not good ay rebounding?",
  "Hope so! Good thing is that autumn is just around the corner.",
  "Fill out this exchange memo, please.",
  "Yes, I have my list.",
  "I've just started doing my clothes here.",
  "Yes, this is very light. But the handle is also aluminum.",
  "I am looking for a pan.",
  "Does the internet come up at all?",
  "It is so very kind of you. I'm so moved by you.",
  "And do you have any questions?",
  "Your food tastes so much better than mine.",
  "Hi! Dear! I'm waiting for you.",
  "Oh, it's really a drag.",
  "It is great. But Tom's bike is so much better than mine.",
  "I wish everything in life was so simple. Thank you.",
  "About a pack, more if I drink.",
  "I'm afraid that a button is missing.",
  "I think Andy's party will be fun.",
  "We can't be too cautious about these things.",
  "I'd like to get this prescription filled.",
  "That settles it then. 5,000 RIB it is, thanks.",
  "I agree! I cried for a week when they broke up.",
  "Yes, I'm leaving at four pm.",
  "Good morning, Nathaniel. This is Leah calling from the International Student Office.",
  "Forgive me darling. I'm very tired.",
  "How long have you been in China?",
  "OK. I will pay it by my bank card.",
  "Ok. That sounds like a deal.",
  "I would like to register for a class today.",
  "What functions does this watch have?",
  "We must set 1000 dollars aside each month.",
  "We'd like to be seated at 8p m.",
  "Is there anything wrong with your food this evening, Miss?",
  "Actually, I'd prefer not to be.",
  "Do they have a lot of equipment?",
  "Would you please countersign them here?",
  "Your tree looks beautiful. Do you decorate it this way every year?",
  "Who do you think that has the motive?",
  "How do I log on to the computer?",
  "Could you arrange a meeting with your boss?",
  "What a cool see-through blue! How do you wear this thing?",
  "What a pity. Can you recommend a nice restaurant near here?",
  "Yeah, most of the people are from my office.",
  "It's still stocked, and there's plenty of ice. Here you are-cheers!",
  "I guess that's OK. What time should I check in?",
  "With pleasure. What color do you like?",
  "Really? You are so kind.",
  "Have fun getting ripped off!",
  "Can I try it on?",
  "Yes, sure. Which cupboard is it in?",
  "I'm fine. I'm just so touched by the sad story.",
  "Let me examine you.Don't worry.It's nothing serious.",
  "All right, sir. You should receive your dinner in about ten minutes.",
  "I haven't rented it out yet. Would you like to see it?",
  "That's enough for the kids. Get some drinks.",
  "How have you been feeling lately?",
  "Do you have any seat preferences, sir?",
  "Then you must be interested in disco.",
  "What name is the reservation under?",
  "Mom, where is the remote? I can't find it.",
  "I'd like a beef-burger, a French fries and a milk shake, please.",
  "What do you think of his behaviour yesterday?",
  "Yes, I do. Leave me alone!",
  "But I put my foot down and insisted on her forgetting that.",
  "Yes, but we need some extra charge and some tip, too.",
  "Ok. How about the earliest possible shipment?",
  "Could we have the honor of you presence of the meeting?",
  "Hello. Can I speak to Alice, please?",
  "I've seen her on TV but not in the flesh.",
  "No matter what, you are still my hero, Daniel.",
  "Could I see that, please?",
  "I am sorry, I don't know.",
  "If you plan on eating, you are.",
  "Hello, I'm looking for a shop that sells inexpensive cashmere sweaters.",
  "This small town has many serious problems.",
  "I see! How many pieces of cake did you eat?",
  "Of course not.There are so many people here today.",
  "Yes. I'd like to book a double room with bath.",
  "What would you do without me?",
  "Yes, great. I am happy you are coming.",
  "Bill. Bill! You gotta help me!",
  "Sorry, I'm not really that interested in those things.",
  "Can you give me a hand, Tom?",
  "Are there any scenic spots nearby?",
  "There is a warrant out for your arrest.",
  "Lily! Why aren't you up and ready for school?",
  "Then I will buy some tomorrow.",
  "Would you please let me know when we get there?",
  "What color is your new dress?",
  "Sure, that would be a good place for them.",
  "I want my hair to be only a few inches long.",
  "We've already cut down our price to cost level.",
  "Sorry, I've got people coming over tomorrow night.",
  "What are you most nervous about?",
  "Jack! Do you want to see a picture of my new puppy?",
  "How was your trip to America?",
  "Some grape juice would also be nice.",
  "Oh, I'm sorry to hear that, sir.What exactly is problem?",
  "What size do you want?",
  "OK. Can I serve you anything else?",
  "Would you like to book a table, sir?",
  "Really? I don't believe I would met him, is he here now?",
  "How about the lunch break, Lucy?",
  "But I think I can help to fix it.",
  "You should try other fundraisers.",
  "Did you guys go on a date already?",
  "I'm too fat for a bikini.",
  "Would you like me to tell you where I got mine.",
  "Sorry, sir. We can't cash the checks for you without your passport.",
  "Oh. What about Saturday? Are you free then?",
  "No, you can learn a lot from them.",
  "So do you think I can take it?",
  "Oh, very beautiful. Thank you, Steven, I like it very much.",
  "Maybe we did miss our stop.",
  "Excuse me, are you Miss Green?",
  "Good afternoon, anything I can do for you?",
  "So Chinese people prefer soccer or basketball?",
  "not yet. I am still looking through the classifieds. Wish me luck.",
  "Could I have a look at those pens?",
  "Yes, I want to know about the Normandy Landing.",
  "What? 100 US dollars? Is it covered by the insurance?",
  "I want to have a continental breakfast.",
  "Do you prepare some dessert for me?",
  "What made you make a decision to leave?",
  "So what are you trying to say to me?",
  "Good afternoon. Is this the Roley Hotel?",
  "Yeah, why not. Do you have all the ingredients?",
  "Thank you so much. Have you got a credit card, Mr. Sandals?",
  "I'm afraid there has been a mistake.",
  "Yeah, it stretches over for thousands of miles.",
  "When do you go to bed usually?",
  "I've been craving chicken and potatoes.",
  "How did you feel about the food?",
  "No, before the In dynasty.",
  "What is your least favorite ice cream?",
  "Yeah. My whole GPA is screwed up now.",
  "Here is the 6,100 RIB.",
  "My native place is Shanghai, which is a very beautiful cosmopolitan city.",
  "It's almost Christmas. What are you doing this weekend?",
  "I see. What about transport? How does Shanghai compare to London?",
  "Where do most of them come from?",
  "Fine. Now complete this form and sign your name at the bottom.",
  "It was really fun chatting with you.",
  "Here we can exchange HAD, USD and Euros. Which do you require?",
  "what a nice garden! Look at these tulips!",
  "Yes. I've got a small room.",
  "Is there anything available for tonight?",
  "Have we got any beer and wine?",
  "Well... thanks, Marcia.It's very nice of you to say so. I mean...",
  "Such as fat-free milk, whole-wheat rolls and fish sandwich.",
  "Good. Do you know anything about this company?",
  "She sure knows how to strut her stuff.",
  "You can exchange this dress with anything of the same value.",
  "How do you know? I thought Taiwanese people didn't have garage sales.",
  "So how do you like it?",
  "Henry, do you know how much we spent this month?",
  "Four by six will do.",
  "There you can see british leaders, entertainers, criminals, and royalty.",
  "no, I can handle it. Thanks anyway.",
  "Can you tell me the calling number, please?",
  "They're all so thin! Her cheekbones are great.",
  "Would you like to get in shape together?",
  "Come on, 18 points already, they are never gonna catch up.",
  "really? so you don't have fried food at all.",
  "I'll bet you were hungry!",
  "How are you doing today? How many in your book today?",
  "Barker? With a B. Of course.",
  "Do you know where they will go on their honeymoon?",
  "Have you gone bowling before?",
  "Eating here or to go?",
  "That's too bad. What problems are you having.",
  "No, I really must go now.My family are expecting me home soon.",
  "Yes, I'll be glad to.",
  "Hey Matt. I just got a job at a consulting firm.",
  "Would you like anything else, sir?",
  "Do you have one of better quality?",
  "Good luck on your first election.",
  "You are welcome. Looking forward to seeing you again.",
  "Can you describe your health concern?",
  "Tom... you are her boss, you kown.Of course, she's helpful to you.",
  "Many times. I'm really addicted. It's harder to stop than you think.",
  "No, I'm not.you can just drive slowly and carefully.",
  "I feel horrible. I think I picked up a bug.",
  "Ha-ha. I get it. That's funny. Your cousin's a real sarcastic lady.",
  "I think I'm your lucky fellow.",
  "Then go up Garden Road, past the Cathedral.",
  "What kind of food do you like?",
  "Hey John, did you register for classes yet?",
  "Shift it a little before you get up.",
  "Out of those what is your favorite?",
  "Are you serious? Fighting? But I didn't hear anything on the news.",
  "What kinds of meat are most popular in your country?",
  "Well, it is getting pretty late. I think we should go home.",
  "Do you mean lying to people for their good?",
  "But I think they're dull, aren't they?",
  "Rents are very high in downtown area.",
  "Have you ever been to any other country?",
  "Hello, IMPF Bank, how can I help you?",
  "I'm not sure I understand.",
  "I'll get on that right away!",
  "Can I see your ticket?",
  "How long will this flight last?",
  "Excuse me. I seem to have lost my son.",
  "You're right, sir. Please let me transfer you to my supervisor",
  "We cannot judge a man totally by that.",
  "Did you? And what course did you take there?",
  "Terrible. How about people's lives?",
  "Must be one smart guy.",
  "That's rock and roll with fast tempo.",
  "What flavor would you like?",
  "We've just started a new business at this bank, Bank-Insurance Link.",
  "Yes, they're fine. I suppose.the server might be down again.",
  "What did you need to talk about?",
  "Good idea. We can finish this project the first thing tomorrow morning.",
  "What else I've got to do? Join the army?",
  "It is impossible. You cheated on me.",
  "Shall I get you another cup of coffee?",
  "Would you like to join the drama club?",
  "I'm okay, thank you. I already checked out the address on MapQuest.",
  "Thank you.That's the result of exercise.By the way, do you work out?",
  "I must ask you to pick him out of a line-up.",
  "sure. I'll just have a bite.",
  "Well, this one might work for you.",
  "No, double B for Bravo",
  "Of course, which room number is it?",
  "I've made a tough decision, sir. Here's my resignation.",
  "I drove a car before, but only once.",
  "You know how to draw and paint?",
  "Go with a hammerhead then-espresso mixed with drip coffee.",
  "We are tired of jobs and competition. We need a quiet place.",
  "Yes. We set up the new alarm system a few months ago.",
  "I will call you when a computer is free.",
  "that's nice. What do they have you doing over there?",
  "do you mind if I sit here?",
  "Absolutely not! I'm not a thief.",
  "Sure. Go back and take the third turning on the left.",
  "This is the menu. Are you ready to order now?",
  "I'm so excited. Finally, a yard of my own.",
  "Yes, that is today's sale price.",
  "You deserve credit, too. I've learned so much from You.",
  "Do you like jazz, Tom?",
  "How about adding some pictures of our products for the introduction?",
  "Sure, how much do you need?",
  "Welcome, Ron, come on in!",
  "Have you filled out an application form?",
  "what about a factory tour?",
  "Could you introduce your biggest accomplishments in your last job?",
  "Leave it to me. I know exactly where to find it.",
  "Pleased to meet you too, Ms Jenson.",
  "Yes, to tell you the truth, there is.",
  "Hey honey, how was your day?",
  "Yes. You must put on her name and address.",
  "I really wish the weather would just stay the same.",
  "Oh, that's terrible. Is it your right arm or your left arm?",
  "Well, I guess you're out of luck.",
  "Hi, Lucy, are you free to talk?",
  "why are women allowed so much more time for maternity leave?",
  "So where should we go?",
  "Yes, will that be possible?",
  "What do these other letters mean?",
  "Good morning. Vane Theater, at your service.",
  "Do you have some points to bring up?",
  "I like them. Do you have matching belts?",
  "Did you want to do something tomorrow?",
  "You'll find our prices very favorable.",
  "Oh, right.Thanks for your help.",
  "Besides, remember to make acknowledgments through an E-mail or a call.",
  "Your meal will be delivered as soon as it's all ready. Enjoy!",
  "oh, maybe I can take the bus or even rent a car.",
  "Really? Thank you. I am thinking the same thing about you.",
  "Who's your manager? Tell me! Would you?",
  "Yes. I'll have a mixed green salad.",
  "Sorry. You know the rules.",
  "Do you need a single apartment, or is this for two people?",
  "It took three of us to move it.",
  "Yes. I have to change a room.",
  "And I couldn't find another phone.",
  "That's incredible! She has such a sharp figure.",
  "What is this, the new Ford?",
  "Isn't your family name Lin?",
  "Oh, it's the first of April, April fool's day",
  "Give me enough for a skirt, will you?",
  "Tell me if you need help.",
  "I'll try. I'm under a lot of pressure right now.",
  "All this is thanks to the efforts of my superiors and colleagues.",
  "Did you hear about Joe? She hasn't eaten for days.",
  "Here is the money, keep the change.",
  "Should I take my shoes off?",
  "Well, how do I look in this one?",
  "I don't have to worry about rent. I live right here.",
  "Seeing as they were late, that won't be a problem.",
  "Sure, in order not to leave a bad impression on the interviewer.",
  "Hey! I have a surprise for you.",
  "You need to sign the paperwork.",
  "Yes, I speak a little French and Japanese.",
  "It was a great idea to spend a day watching a game.",
  "But I think time can change everything.",
  "How would you describe your relationship with your last two supervisors?",
  "Sure, I'll take mine, sunny side up.",
  "No. I'm thinking that maybe I can get my hair shampooed.",
  "Tom got along well with classmates. He is really a good boy.",
  "Do you expect a high salary?",
  "Actually, I'm not good at tennis at all...",
  "Just roll it up and have a bite, Amy.",
  "Yeah. It's already December, you know.",
  "I don't have this kind of software.",
  "Yeah, I really want it. I am on my uppers.",
  "Hey, what's good with you?",
  "Yes I see. But you decided to leave them in 2006, right?",
  "Even if it doesn't work, it's a beautiful collectible.",
  "Are you still busy today?",
  "The phone number is 328 6765 extension 105.",
  "Well, I want to change 1000 Australian dollars for RIB.",
  "Hi! This is Jill.How come you didn't come in today?",
  "What time would you like to take the test?",
  "Will the blood test hurt?",
  "I didn't sleep a wink last night.",
  "Henry married Rose only after her father's money, didn't he?",
  "No, thank you. I think I can handle it.",
  "Look at that pretty girl.",
  "A debit card will be fine.",
  "Which train do you catch in the evening?",
  "I'd like to reserve a table for three this evening.",
  "I'm very much interested in the position.",
  "Friday sounds good. Where should we meet?",
  "We'd like to buy some furniture for our new house.",
  "She dropped out of school completely.",
  "yep. Here it is. What do you think?",
  "yes, yes, he's right here by me.",
  "will the train be very crowded?",
  "I'm in 507, and I have a big problem.",
  "I hope so. But I'm always caught short.",
  "Daniel loves the beach very much!",
  "Does she make any sense to you?",
  "How long will it take? We are in a great hurry.",
  "It is stupid to say so.",
  "Let me know if I can help.",
  "How long was she employed with your company?",
  "Alright. We are out of everything.",
  "Would you like anything else?",
  "What is the best way to find a job here?",
  "Driver, take me to the airport.",
  "Okay. Good night. Have a good dream.",
  "Ok, would you like some soup as well?",
  "Hello, what can I do for you today?",
  "That would take care of it, thank you.",
  "Forest Restaurant. What can I do for you?",
  "Well, then join us some other time.",
  "Really, who started the argument?",
  "Yes, miss. What was the problem with your purchase?",
  "It's got chickpeas and vegetables in a spicy curry sauce with rice.",
  "Hi, Mary, long time no see.",
  "That's cool. Care for a little quiz on that?",
  "Get me a medium Pepsi.",
  "Yes. Here's my card. Do you need my ID?",
  "Are you on the level? You're the one who called me, remember?",
  "how would you decorate your house?",
  "Tell me what you've been doing.",
  "Could I have your name, please?",
  "Sounds fine to me. Whatever, let's enjoy this pond first.",
  "He had a mask over his face.",
  "Yes, the Forrest's experience can encourage the people in trouble.",
  "Have you ever had snow in your city?",
  "Oh, they are playing the wedding March. Here they come.",
  "well, I quit and gained it back plus 5 pounds.",
  "Tom, I married Julia last month. Have you already known it?",
  "Sounds good. When and where shall we meet?",
  "It looks okay to me.",
  "I'd like it to look simple, neat and relaxing.",
  "And they can deal with everything?",
  "Okay, sir. Three of each. Would you like anything else?",
  "Do you know anything about Britain and America?",
  "He was wearing a mask.",
  "The general manager of your section.",
  "Please? I haven't eaten anything all day.",
  "how long is your contract for?",
  "Will you be getting more in.",
  "I hope my baggage aren't overweight.",
  "Really? You've done a good job.",
  "It depends on how much you order",
  "Let's meet tonight at the Thai restaurant at about 5.",
  "Sure. We love each other and take care of each other.",
  "So you don't travel a lot now?",
  "Yes, but there is a five dollars delivery charge.",
  "Yes, I'm looking for a book on Chinese history.",
  "A Mac it is. I'll take one home with me.",
  "All right.How about this one?",
  "Our relationship. I mean my friend and I...",
  "Good morning! I'm Steven Smith. I want to open an account here.",
  "No, no, for the engagement.",
  "OK, I'll get it. It's for you, Jeff.",
  "I see. What is today's schedule?",
  "Don't you have any Chinese food?",
  "This pair is Rolex, right?",
  "Yes. Well, I think I'll go get lunch. Will you join me?",
  "No, but I'll be able to tomorrow.",
  "You know. I really don't those big hotels.",
  "I'm a comparative literature major.",
  "Yeah, I want the note.",
  "Is that building a perfect cube?",
  "I am calling to say thank you for the interview yesterday.",
  "Oh, it's really beautiful, but I just can't dance it well.",
  "Well, do you like novels?",
  "Yes, but sometimes he is just not reasonable.",
  "Okay. Full-size, mid-size or compact, ma'am?",
  "Were you in or out? Can you remember that?",
  "Thanks. It was very nice to meet you.",
  "It is a six-hour flight with an-hour layover in Los Angles.",
  "Are all lucky people so stuck up?",
  "No. Just talk to your manager and let me know.",
  "We need to elect club officials before the summer starts.",
  "The oceans and landscapes all influence our climate.",
  "Oh, just olives please. What music is this?",
  "Wow, they were good. I guess criminals aren't that dumb after all.",
  "In that case, take the basket outside and empty it.",
  "The time of departure will be announced as soon as possible.",
  "That's because we have a strong lock.",
  "I think so.Here it is.It's by the basin.",
  "Thank you. We'd like to have some dessert.",
  "Thank you for your letter.",
  "What do you mean it should?",
  "How many hours would I work a day and what's the pay?",
  "Don't be silly. Let's go Dutch.",
  "Thank you.But does it really look all right?",
  "Yes, it is the credit demand.Where can I cash travellers'cheques?",
  "So do you! How are you doing?",
  "Harry. He has been assisting me on the plan.",
  "See you on Moday.Have a great weekend.",
  "My mother is a professor and my father is a manager.",
  "No, I left it at home.Sorry!",
  "Good evening, Mr. Frank. Bourbon on the rocks?",
  "Did you enjoy the meal?",
  "Fine then, what time are we going to leave?",
  "Where are you going, Tony?",
  "how do you know her?",
  "Jane. Nice to meet you.",
  "E-A-K-I-N-S.First name, Donald.And what's your present address, Mr.Eakins?",
  "Yeah. People always enjoy the lighted lanterns and the gala performances.",
  "I want to open a current account.",
  "What does my white blood cell count tell him?",
  "That's a good idea. Wish you a great vacation!",
  "That's okay. Well, let me think. How about a mystery novel?",
  "yes, on a business trip. How about you?",
  "No, I don't. But I do know where the shopping mall is.",
  "This is Mr.Gao. How are you?",
  "Are you ready to move?",
  "And how much is the coca cola?",
  "Can I pay by private check?",
  "For me? The football games of course, I love football games.",
  "No, I first came here 1995.",
  "Really? Can I join it?",
  "Do you have life insurance?",
  "Oh, My chance is slim then.",
  "It doesn't sound like an English word.",
  "The rent is 400 yuan a day.",
  "Oh. Did you pick up the suits from the cleaners?",
  "Yes, Thursday would be fine. What time shall I come?",
  "I just have some cereal each morning.",
  "Well first put your money in.",
  "How many did you use to take?",
  "I believe industry is making us wealthier.",
  "I am afraid not. Right now it's the tour season.",
  "Oh, it's a pity that you have to leave.",
  "Fine, just fine. And you?",
  "I don't really like sci-fi movies because they're always really weird.",
  "How much does that cost?",
  "Which kind of sport do you like to watch?",
  "Very big and exciting, but very crowded, too.",
  "So you have to apply to begin the first semester next year.",
  "Good idea. How much do I need to deposit?",
  "Hello, is that Cathy speaking?",
  "I need to check these books out.",
  "What time does the office close?",
  "OK, anyway, let me have it.",
  "No, not really. Why do you ask?",
  "No. Not at all. I'm quite easy-going.",
];

function getRandomSentence(usedIds) {
  const available = SENTENCES.map((s, idx) => ({ id: idx, text: s })).filter(s => !usedIds.includes(s.id));
  if (available.length === 0) return null; // out of sentences
  const random = available[Math.floor(Math.random() * available.length)];
  return {
    id: random.id,
    answer: random.text,
    words: shuffle(random.text.split(' '))
  };
}

function shuffle(array) {
  let currentIndex = array.length, randomIndex;
  while (currentIndex !== 0) {
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;
    [array[currentIndex], array[randomIndex]] = [array[randomIndex], array[currentIndex]];
  }
  return array;
}

function normalizeSentence(text) {
  return String(text)
    .trim()
    .replace(/\s+/g, " ")
    .toLowerCase()
    .replace(/[.,?!]/g, ""); // strip punctuation for flexible matching
}

function getMatchSentences(count = 5) {
  const sequence = [];
  const usedIds = [];
  for (let i = 0; i < count; i++) {
    const s = getRandomSentence(usedIds);
    if (s) {
      sequence.push(s);
      usedIds.push(s.id);
    }
  }
  return sequence;
}

module.exports = {
  getRandomSentence,
  normalizeSentence,
  getMatchSentences
};
